### ISSUE TITLE
Internet Explorer 11  comment

### ISSUE THREAD

**Issue by AnnaAmelia** [MicrosoftDocs/powerbi-docs.de-de#11]
[Hier Feedback eingeben]
This newly added comment "Internet Explorer 11 is only supported when using SharePoint Online. You may use other support browsers in either scenario." is not available in de-de version of the article, only en-us. 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 4f0c4f04-7975-0f89-d5db-7b3e3a5b42f6
* Version Independent ID: b2c4c36e-c00e-ba79-8dc6-df56c696be2c
* Content: [Einbetten eines Power BI-Berichtsserver-Berichts in einen iFrame in SharePoint Server - Power BI](https://docs.microsoft.com/de-de/power-bi/report-server/quickstart-embed#feedback)
* Content Source: [powerbi-docs/report-server/quickstart-embed.md](https://github.com/MicrosoftDocs/powerbi-docs.de-de/blob/live/powerbi-docs/report-server/quickstart-embed.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by srvbpigh** [comment]
Hello, @AnnaAmelia
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @AnnaAmelia

Thank you for your feedback and suggestion.  

The file is currently under localization process. We will release this article soon.

Many thanks for your support. 

Kind regards,

Microsoft DOCS Global Experience Team
