### ISSUE TITLE
Deutschland Regionenschlüssel fehlerhaft

### ISSUE THREAD

**Issue by Flo199** [MicrosoftDocs/powerbi-docs.de-de#14]
Hi,

Vielen Dank für den hilfreichen Artikel. Leider funktioniert bei mir der Regionenschlüssel zu Deutschland nur tlw da die Bundesländer Schleswig-Holstein und Baden-Würtemberg nur Städten zugeordnet werden und nicht den Bundesländern (Baden-Würtemberg wird Baden-Baden zugeordnet und Schleswig-Holstein wird Schleswig zugeordnet). Habt ihr hierzu eine Lösung?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 6a301928-35b6-2b9d-3bbe-0dc48b237b07
* Version Independent ID: 765bad52-68e2-985f-924e-4e7f334b62f0
* Content: [Verwenden von Flächenkartogrammen in Power BI Desktop (Vorschauversion) - Power BI](https://docs.microsoft.com/de-de/power-bi/visuals/desktop-shape-map)
* Content Source: [powerbi-docs/visuals/desktop-shape-map.md](https://github.com/MicrosoftDocs/powerbi-docs.de-de/blob/live/powerbi-docs/visuals/desktop-shape-map.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @mihart
* Microsoft Alias: **rien**

**Comment by srvbpigh** [comment]
Hello, @Flo199
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hallo @Flo199 

wir schätzen Ihre Beiträge. Da dieses Feedback sich jedoch auf ein Produkt bezieht, sollten Sie Ihren Vorschlag über die Schaltfläche „Dieses Produkt“ am Ende der Dokumentationsseite einreichen.

Wenn Sie Feedback zur Dokumentation haben, können Sie es über diesen Kanal einreichen.

Wir schätzen Ihre Beiträge zu unseren Artikeln.
