### ISSUE TITLE
Creating Power BI reports in Report Server

### ISSUE THREAD

**Issue by mrksrngs** [MicrosoftDocs/powerbi-docs.de-de#5]
Hello, is it planned to allow the creation of Power BI reports in the Report Server?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: a5e43027-f0e6-928a-8c16-4401ee8d0e52
* Version Independent ID: 51c87d50-4316-c0d9-a31c-3163d1557e1f
* Content: [Vergleich zwischen Power BI-Berichtsserver und Power BI-Dienst - Power BI](https://docs.microsoft.com/de-de/power-bi/report-server/compare-report-server-service#feedback)
* Content Source: [powerbi-docs/report-server/compare-report-server-service.md](https://github.com/MicrosoftDocs/powerbi-docs.de-de/blob/live/powerbi-docs/report-server/compare-report-server-service.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @markingmyname
* Microsoft Alias: **maghan**

**Comment by CeciAc** [comment]
Hello, @mrksrngs

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
