### ISSUE TITLE
Keine Rechte

### ISSUE THREAD

**Issue by heidiweber** [MicrosoftDocs/powerbi-docs.de-de#8]
Leider funktioniert die Übung nicht, da facebook den Zugriff verwehrt.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 121b33bb-7721-3f2e-e863-ad5ef222b71f
* Version Independent ID: 023070b1-753a-f9c2-7924-a350d7480a22
* Content: [Tutorial: Facebook-Analysen mit Power BI Desktop - Power BI](https://docs.microsoft.com/de-de/power-bi/desktop-tutorial-facebook-analytics#feedback)
* Content Source: [powerbi-docs/desktop-tutorial-facebook-analytics.md](https://github.com/MicrosoftDocs/powerbi-docs.de-de/blob/live/powerbi-docs/desktop-tutorial-facebook-analytics.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by srvbpigh** [comment]
Hello, @heidiweber
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @heidiweber

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
