### ISSUE TITLE
Change color of whole row

### ISSUE THREAD

**Issue by Niyo** [MicrosoftDocs/powerbi-docs.de-de#9]
How can I change the color of a whole row? Or isn't this possible?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 3af9ce3a-a3eb-8d57-55a7-66f04f46bbf7
* Version Independent ID: 58e304ed-89d2-3c85-4428-acefedaef5c0
* Content: [Bedingte Tabellenformatierungen in Power BI Desktop - Power BI](https://docs.microsoft.com/de-de/power-bi/desktop-conditional-table-formatting)
* Content Source: [powerbi-docs/desktop-conditional-table-formatting.md](https://github.com/MicrosoftDocs/powerbi-docs.de-de/blob/live/powerbi-docs/desktop-conditional-table-formatting.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by srvbpigh** [comment]
Hello, @Niyo
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @Niyo 

Your contribution is much appreciated. Yet, this feedback is related with product, please kindly log by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles.
	
Kind regards,
Microsoft DOCS International Team
